erver:
  port: 8090
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 6
    password: 12345678
    timeout: 3000
    jedis:
      pool:
        max-active: 50
        min-idle: 5
        max-wait: 3000
        max-idle: 20